# Generated by Django 4.2.13 on 2024-05-25 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnitz_api_backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('address1', models.CharField(blank=True, max_length=100)),
                ('address2', models.CharField(blank=True, max_length=100)),
                ('address3', models.CharField(blank=True, max_length=100)),
                ('role', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'power_user'), (2, 'regular_user')], default=3, null=True)),
            ],
        ),
    ]
