# Generated by Django 4.2.13 on 2024-06-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnitz_api_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jugendberufshilfen',
            name='CATEGORY_ID',
            field=models.CharField(default='3', max_length=100),
        ),
        migrations.AddField(
            model_name='kindergarten',
            name='CATEGORY_ID',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AddField(
            model_name='schulen',
            name='CATEGORY_ID',
            field=models.CharField(default='2', max_length=100),
        ),
        migrations.AddField(
            model_name='schulsozialarbeit',
            name='CATEGORY_ID',
            field=models.CharField(default='4', max_length=100),
        ),
    ]
