# Generated by Django 4.2.13 on 2024-06-03 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemnitz_api_backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraddress',
            old_name='place',
            new_name='city',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='street',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='postalcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='street_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='Germany', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='house_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default='Saxony', max_length=100),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='chemnitz_api_backend.users'),
        ),
    ]
