# Generated by Django 4.2.13 on 2024-06-04 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemnitz_api_backend', '0002_rename_place_useraddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='latitude',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='longitude',
            field=models.FloatField(blank=True),
        ),
    ]
