# Generated by Django 4.2.13 on 2024-06-05 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemnitz_api_backend', '0003_alter_favorite_bezeichnung_alter_favorite_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='favorite',
        ),
    ]
