# Generated by Django 4.2.13 on 2024-06-05 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemnitz_api_backend', '0004_remove_users_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jugendberufshilfen',
            name='CATEGORY_ID',
        ),
        migrations.RemoveField(
            model_name='kindergarten',
            name='CATEGORY_ID',
        ),
        migrations.RemoveField(
            model_name='schulen',
            name='CATEGORY_ID',
        ),
        migrations.RemoveField(
            model_name='schulsozialarbeit',
            name='CATEGORY_ID',
        ),
    ]
